import { sqliteTable, text, integer } from 'drizzle-orm/sqlite-core'

export const evaluari = sqliteTable('evaluari', {
  id: text('id').primaryKey(),
  status: text('status', { enum: ['draft', 'completed'] }).notNull().default('draft'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
  completedAt: text('completed_at'),
  denumireProiect: text('denumire_proiect'),
  codProiect: text('cod_proiect'),
  adresaLocatie: text('adresa_locatie'),
  localitate: text('localitate'),
  judet: text('judet'),
  beneficiar: text('beneficiar'),
  cuiBeneficiar: text('cui_beneficiar'),
  antreprenor: text('antreprenor'),
  cuiAntreprenor: text('cui_antreprenor'),
  subantreprenor: text('subantreprenor'),
  fazaLucrarii: text('faza_lucrarii'),
  fazaLucrariiCustom: text('faza_lucrarii_custom'),
  descriereObiectiv: text('descriere_obiectiv'),
  numeEvaluator: text('nume_evaluator'),
  functieEvaluator: text('functie_evaluator'),
  firmaEvaluator: text('firma_evaluator'),
  nrDocument: text('nr_document'),
  dataEvaluarii: text('data_evaluarii'),
  dataRevizuirii: text('data_revizuirii'),
  suprafataTotala: text('suprafata_totala'),
  descriereAmplasare: text('descriere_amplasare'),
  tipImprejmuire: text('tip_imprejmuire'),
  tipAcces: text('tip_acces'),
  vecinNord: text('vecin_nord'),
  vecinEst: text('vecin_est'),
  vecinSud: text('vecin_sud'),
  vecinVest: text('vecin_vest'),
  sefSantier: text('sef_santier'),
  functieSefSantier: text('functie_sef_santier'),
  responsabilSSM: text('responsabil_ssm'),
  functieResponsabilSSM: text('functie_responsabil_ssm'),
  dataAprobarii: text('data_aprobarii'),
  observatiiGenerale: text('observatii_generale'),
  documenteAplicabile: text('documente_aplicabile'),
  anexeSelectate: text('anexe_selectate'),
  observatiiDocumente: text('observatii_documente'),
})

export const riscuri = sqliteTable('riscuri', {
  id: text('id').primaryKey(),
  evaluareId: text('evaluare_id')
    .notNull()
    .references(() => evaluari.id, { onDelete: 'cascade' }),
  ordine: integer('ordine').notNull().default(0),
  activitate: text('activitate'),
  activitateCustom: text('activitate_custom'),
  pericol: text('pericol'),
  pericolCustom: text('pericol_custom'),
  descrierePericol: text('descriere_pericol'),
  persoaneExpuse: text('persoane_expuse'),
  numarPersoaneExpuse: integer('numar_persoane_expuse'),
  probabilitateInitiala: integer('probabilitate_initiala'),
  severitateInitiala: integer('severitate_initiala'),
  masuriExistente: text('masuri_existente'),
  masuriExistenteCustom: text('masuri_existente_custom'),
  masuriSuplimentare: text('masuri_suplimentare'),
  probabilitateReziduala: integer('probabilitate_reziduala'),
  severitateReziduala: integer('severitate_reziduala'),
  responsabilImplementare: text('responsabil_implementare'),
  functieResponsabil: text('functie_responsabil'),
  termenImplementare: text('termen_implementare'),
  statusRisc: text('status_risc', { enum: ['deschis', 'in_lucru', 'inchis'] })
    .notNull()
    .default('deschis'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
})

export const templates = sqliteTable('templates', {
  id: text('id').primaryKey(),
  nume: text('nume').notNull(),
  descriere: text('descriere'),
  continut: text('continut').notNull(),
  createdAt: text('created_at').notNull(),
})
