import { sqliteTable, text, integer } from 'drizzle-orm/sqlite-core'

export const users = sqliteTable('users', {
  id: text('id').primaryKey(),
  email: text('email').unique().notNull(),
  name: text('name').notNull(),
  passwordHash: text('password_hash').notNull(),
  role: text('role', { enum: ['evaluator', 'admin'] })
    .notNull()
    .default('evaluator'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
})

export const evaluari = sqliteTable('evaluari', {
  id: text('id').primaryKey(),
  userId: text('user_id').references(() => users.id),
  status: text('status', { enum: ['draft', 'completed'] }).notNull().default('draft'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
  completedAt: text('completed_at'),
  denumireProiect: text('denumire_proiect'),
  codProiect: text('cod_proiect'),
  adresaLocatie: text('adresa_locatie'),
  localitate: text('localitate'),
  judet: text('judet'),
  beneficiar: text('beneficiar'),
  cuiBeneficiar: text('cui_beneficiar'),
  antreprenor: text('antreprenor'),
  cuiAntreprenor: text('cui_antreprenor'),
  subantreprenor: text('subantreprenor'),
  fazaLucrarii: text('faza_lucrarii'),
  fazaLucrariiCustom: text('faza_lucrarii_custom'),
  descriereObiectiv: text('descriere_obiectiv'),
  numeEvaluator: text('nume_evaluator'),
  functieEvaluator: text('functie_evaluator'),
  firmaEvaluator: text('firma_evaluator'),
  nrDocument: text('nr_document'),
  dataEvaluarii: text('data_evaluarii'),
  dataRevizuirii: text('data_revizuirii'),
  tipEvaluare: text('tip_evaluare'),
  obiectiveEvaluare: text('obiective_evaluare'),
  metodeInstrumente: text('metode_instrumente'),
  suprafataTotala: text('suprafata_totala'),
  descriereAmplasare: text('descriere_amplasare'),
  tipImprejmuire: text('tip_imprejmuire'),
  tipAcces: text('tip_acces'),
  vecinNord: text('vecin_nord'),
  vecinEst: text('vecin_est'),
  vecinSud: text('vecin_sud'),
  vecinVest: text('vecin_vest'),
  sefSantier: text('sef_santier'),
  functieSefSantier: text('functie_sef_santier'),
  responsabilSSM: text('responsabil_ssm'),
  functieResponsabilSSM: text('functie_responsabil_ssm'),
  dataAprobarii: text('data_aprobarii'),
  observatiiGenerale: text('observatii_generale'),
  documenteAplicabile: text('documente_aplicabile'),
  anexeSelectate: text('anexe_selectate'),
  observatiiDocumente: text('observatii_documente'),
  // Cadru Organizațional Intern (Cap. III)
  cadruRegimActivitate: text('cadru_regim_activitate'),
  cadruProgramLucru: text('cadru_program_lucru'),
  cadruFluxPersoane: text('cadru_flux_persoane'),
  cadruFluxBunuri: text('cadru_flux_bunuri'),
  cadruNumarAngajati: integer('cadru_numar_angajati'),
  cadruZoneFunctionale: text('cadru_zone_functionale'),
  cadruBunuriValori: text('cadru_bunuri_valori'),
  cadruSistemeTehnice: text('cadru_sisteme_tehnice'),
  cadruFactoriVulnerabilitate: text('cadru_factori_vulnerabilitate'),
  // Amplasare & Factori Externi (additional fields)
  numarPuncteAcces: integer('numar_puncte_acces'),
  caiAcces: text('cai_acces'),
  posibilitateDisimulare: text('posibilitate_disimulare'),
  vecinatatiBifate: text('vecinatati_bifate'),
  factoriExterni: text('factori_externi'),
  istoricIncidente: text('istoric_incidente'),
  // Măsuri & Mecanisme de Securitate (Cap. V)
  masuriMecanofizice: text('masuri_mecanofizice'),
  masuriControlAcces: text('masuri_control_acces'),
  masuriAlarmare: text('masuri_alarmare'),
  masuriCctv: text('masuri_cctv'),
  pazaUmana: text('paza_umana'),
  numarAgenti: integer('numar_agenti'),
  masuriOrganizatorice: text('masuri_organizatorice'),
  masuriAsigurari: text('masuri_asigurari'),
  observatiiMasuri: text('observatii_masuri'),
  // Concluzii (Cap. VI)
  nivelRiscGlobalAsumat: text('nivel_risc_global_asumat'),
  nivelRiscRezidualGlobal: text('nivel_risc_rezidual_global'),
  termenImplementareGlobal: text('termen_implementare_global'),
  concluziiGenerale: text('concluzii_generale'),
  masuriObligatorii: text('masuri_obligatorii'),
  masuriRecomandate: text('masuri_recomandate'),
})

export const riscuri = sqliteTable('riscuri', {
  id: text('id').primaryKey(),
  evaluareId: text('evaluare_id')
    .notNull()
    .references(() => evaluari.id, { onDelete: 'cascade' }),
  ordine: integer('ordine').notNull().default(0),
  activitate: text('activitate'),
  activitateCustom: text('activitate_custom'),
  pericol: text('pericol'),
  pericolCustom: text('pericol_custom'),
  descrierePericol: text('descriere_pericol'),
  persoaneExpuse: text('persoane_expuse'),
  numarPersoaneExpuse: integer('numar_persoane_expuse'),
  probabilitateInitiala: integer('probabilitate_initiala'),
  severitateInitiala: integer('severitate_initiala'),
  masuriExistente: text('masuri_existente'),
  masuriExistenteCustom: text('masuri_existente_custom'),
  masuriSuplimentare: text('masuri_suplimentare'),
  probabilitateReziduala: integer('probabilitate_reziduala'),
  severitateReziduala: integer('severitate_reziduala'),
  responsabilImplementare: text('responsabil_implementare'),
  functieResponsabil: text('functie_responsabil'),
  termenImplementare: text('termen_implementare'),
  statusRisc: text('status_risc', { enum: ['deschis', 'in_lucru', 'inchis'] })
    .notNull()
    .default('deschis'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
})

export const templates = sqliteTable('templates', {
  id: text('id').primaryKey(),
  userId: text('user_id').references(() => users.id),
  nume: text('nume').notNull(),
  descriere: text('descriere'),
  continut: text('continut').notNull(),
  createdAt: text('created_at').notNull(),
})
